// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
<<<<<<< HEAD
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
=======
    Address: typeof import('./src/components/vo/Address.vue')['default']
    Author: typeof import('./src/components/Author.vue')['default']
    AuthorGrid: typeof import('./src/components/ui/AuthorGrid.vue')['default']
    AuthorListView: typeof import('./src/components/AuthorListView.vue')['default']
    BaseDetailGrid: typeof import('./src/components/base-ui/BaseDetailGrid.vue')['default']
    BaseEntity: typeof import('./src/components/base-ui/BaseEntity.vue')['default']
    BaseGrid: typeof import('./src/components/base-ui/BaseGrid.vue')['default']
    BasePicker: typeof import('./src/components/base-ui/BasePicker.vue')['default']
    BaseSecurity: typeof import('./src/components/base-ui/BaseSecurity.vue')['default']
    Book: typeof import('./src/components/Book.vue')['default']
    BookGrid: typeof import('./src/components/ui/BookGrid.vue')['default']
    BookListView: typeof import('./src/components/BookListView.vue')['default']
    Boolean: typeof import('./src/components/primitives/Boolean.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    Date: typeof import('./src/components/primitives/Date.vue')['default']
    Email: typeof import('./src/components/vo/Email.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    EventViewer: typeof import('./src/components/vo/EventViewer.vue')['default']
    File: typeof import('./src/components/vo/File.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    LargeObject: typeof import('./src/components/primitives/LargeObject.vue')['default']
    Manuscript: typeof import('./src/components/Manuscript.vue')['default']
    ManuscriptGrid: typeof import('./src/components/ui/ManuscriptGrid.vue')['default']
    ManuscriptListView: typeof import('./src/components/ManuscriptListView.vue')['default']
    Money: typeof import('./src/components/vo/Money.vue')['default']
    Number: typeof import('./src/components/primitives/Number.vue')['default']
    Payment: typeof import('./src/components/vo/Payment.vue')['default']
    PeriodSubscribe: typeof import('./src/components/PeriodSubscribe.vue')['default']
    PeriodSubscribeGrid: typeof import('./src/components/ui/PeriodSubscribeGrid.vue')['default']
    Photo: typeof import('./src/components/vo/Photo.vue')['default']
    Point: typeof import('./src/components/Point.vue')['default']
    PointGrid: typeof import('./src/components/ui/PointGrid.vue')['default']
    PointsListView: typeof import('./src/components/PointsListView.vue')['default']
    Publish: typeof import('./src/components/Publish.vue')['default']
    PublishGrid: typeof import('./src/components/ui/PublishGrid.vue')['default']
    Rating: typeof import('./src/components/vo/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    String: typeof import('./src/components/primitives/String.vue')['default']
    SubscribeListView: typeof import('./src/components/SubscribeListView.vue')['default']
    SubscribeSu: typeof import('./src/components/SubscribeSu.vue')['default']
    SubscribeSuGrid: typeof import('./src/components/ui/SubscribeSuGrid.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    UserGrid: typeof import('./src/components/ui/UserGrid.vue')['default']
    Weather: typeof import('./src/components/vo/Weather.vue')['default']
>>>>>>> cc51f632aa39de85878eeed3e45ae4baeaf95442
  }
}
